Fix linter errors (mypy type checks) (#189)
Summary:
# Description

A recent breaking change in MyPy related to PEP 484 (https://mypy-lang.blogspot.com/2022/11/mypy-0990-released.html) makes linter checks fail.

# Solution

As described on the website, just update any typing in the form of `variable: some_type = None` to `variable: Optional[some_type] = None`, which is equivalent to `variable: Union[some_type, None] = None` or `variable: some_type | None = None` (this last option requires python 3.10.

# Before changes:

```
python3 -m mypy --config-file mypy.ini
aepsych/likelihoods/ordinal.py:18: error: Incompatible default for argument "link" (default has type "None", argument
has type "Callable[..., Any]")  [assignment]
        def __init__(self, n_levels: int, link: Callable = None):
                                                           ^~~~
aepsych/likelihoods/ordinal.py:18: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
aepsych/likelihoods/ordinal.py:18: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
aepsych/likelihoods/ordinal.py:26: error: Function "Callable[..., Any]" could always be true in boolean context
[truthy-function]
            self.link = link or Normal(0, 1).cdf
                        ^~~~
aepsych/models/base.py:272: error: Incompatible default for argument "cred_level" (default has type "None", argument
has type "float")  [assignment]
            cred_level: float = None,
                                ^~~~
aepsych/models/base.py:272: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
aepsych/models/base.py:272: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
aepsych/models/base.py:367: error: Incompatible default for argument "slice_dims" (default has type "None", argument
has type "Mapping[int, float]")  [assignment]
            slice_dims: Mapping[int, float] = None,
                                              ^~~~
aepsych/models/base.py:367: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
aepsych/models/base.py:367: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
aepsych/generators/sobol_generator.py:51: error: Incompatible default for argument "model" (default has type "None",
argument has type "AEPsychMixin")  [assignment]
            model: AEPsychMixin = None,  # included for API compatibility
                                  ^~~~
aepsych/generators/sobol_generator.py:51: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
aepsych/generators/sobol_generator.py:51: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
aepsych/generators/random_generator.py:42: error: Incompatible default for argument "model" (default has type "None",
argument has type "AEPsychMixin")  [assignment]
            model: AEPsychMixin = None,  # included for API compatibility.
                                  ^~~~
aepsych/generators/random_generator.py:42: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
aepsych/generators/random_generator.py:42: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
aepsych/generators/manual_generator.py:50: error: Incompatible default for argument "model" (default has type "None",
argument has type "AEPsychMixin")  [assignment]
            model: AEPsychMixin = None,  # included for API compatibility
                                  ^~~~
aepsych/generators/manual_generator.py:50: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
aepsych/generators/manual_generator.py:50: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
aepsych/plotting.py:326: error: Incompatible default for argument "parnames" (default has type "None", argument has
type "List[str]")  [assignment]
        parnames: List[str] = None,
                              ^~~~
aepsych/plotting.py:326: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
aepsych/plotting.py:326: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
Found 8 errors in 6 files (checked 58 source files)
```

# Aftar changes:
```
python3 -m mypy --config-file mypy.ini
Success: no issues found in 58 source files
```

Pull Request resolved: https://github.com/facebookresearch/aepsych/pull/189

Reviewed By: crasanders

Differential Revision: D41163538

fbshipit-source-id: e33ceae1418bad1afb31a86a3b425bf21baaa709